services:
  db:
    image: postgres:latest
    container_name: postgres_intuitivecare
    environment:
      POSTGRES_USER: intuitivecare
      POSTGRES_PASSWORD: intuitivecare@2025
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
