"""
# Questão 3
# Questão 3
# Questão 3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/100e7MhhjdP2gQBBS69PGS_dhu5Cxendk

Por favor, leia o README.md antes de executar este script.
"""

# Questão 3
# Questão 3
# Questão 3

import pandas as pd
import os
from operacoes_no_db import inserir_dados_no_postgres, visualizar_tabela

pasta_csv = 'documentos/demonstracoes_contabeis'
arquivos = [f for f in os.listdir(pasta_csv) if f.endswith('.csv')]
arquivos.sort()
dfs = []
for arquivo in arquivos:
    caminho_arquivo = os.path.join(pasta_csv, arquivo)
    try:
        df = pd.read_csv(caminho_arquivo, sep=";", encoding="utf-8", on_bad_lines="skip")
        dfs.append(df)
        print(f"✔ Arquivo lido corretamente: {arquivo}")
    except Exception as e:
        print(f"❌ Erro ao ler {arquivo}: {e}")
if not dfs:
    print("Nenhum arquivo pôde ser lido.")
    exit()
df_total = pd.concat(dfs, ignore_index=True)
df_total = df_total.fillna("NULL")
tabela = "demonstracoes_contabeis"
df_total['VL_SALDO_INICIAL'] = df_total['VL_SALDO_INICIAL'].str.replace(',', '.').astype(float)
df_total['VL_SALDO_FINAL'] = df_total['VL_SALDO_FINAL'].str.replace(',', '.').astype(float)
csv_file = "demonstracoes_contabeis.csv"
df_total.to_csv(csv_file, sep=';', index=False, header=False, encoding='utf-8', decimal='.')

sql_file = "import.sql"

print("\n")
print(f"CSV gerado: {csv_file}")
print("\n")

deseja_importar = input("Você deseja executar o comando para importar os dados para o banco de dados (Postgres)? (Digite 'sim' para executar ou 'não' para cancelar): ")
if deseja_importar.lower() == 'sim':
    inserir_dados_no_postgres()
else:
    print("Ação cancelada.")
    
deseja_visualizar = input("Você deseja visualizar a tabela 'demonstracoes_contabeis' no banco de dados (Postgres)? (Digite 'sim' para visualizar ou 'não' para cancelar): ")
if deseja_visualizar.lower() == 'sim':
    visualizar_tabela(10)    
else:
    print("Ação cancelada.")
