# -*- coding: utf-8 -*-
"""Questao3_intuitivecare.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/100e7MhhjdP2gQBBS69PGS_dhu5Cxendk
"""

import pandas as pd
import os
from inserir_dados_no_banco import inserir_dados_no_postgres

pasta_csv = 'documentos/trimestres'
arquivos = [f for f in os.listdir(pasta_csv) if f.endswith('.csv')]
dfs = []
for arquivo in arquivos:
    caminho_arquivo = os.path.join(pasta_csv, arquivo)
    try:
        df = pd.read_csv(caminho_arquivo, sep=";", encoding="utf-8", on_bad_lines="skip")
        dfs.append(df)
        print(f"✔ Arquivo lido corretamente: {arquivo}")
    except Exception as e:
        print(f"❌ Erro ao ler {arquivo}: {e}")
if not dfs:
    print("Nenhum arquivo pôde ser lido.")
    exit()
df_total = pd.concat(dfs, ignore_index=True)
df_total = df_total.fillna("NULL")
tabela = "demonstracoes_contabeis"
csv_file = "dados.csv"
df_total['VL_SALDO_INICIAL'] = df_total['VL_SALDO_INICIAL'].str.replace(',', '.').astype(float)
df_total['VL_SALDO_FINAL'] = df_total['VL_SALDO_FINAL'].str.replace(',', '.').astype(float)
df_total.to_csv(csv_file, sep=';', index=False, header=False, encoding='utf-8', decimal='.')
sql_file = "import.sql"
with open(sql_file, "w", encoding="utf-8") as f:
    f.write(""" 
    CREATE TABLE IF NOT EXISTS demonstracoes_contabeis (
        DATA DATE,
        REG_ANS BIGINT,
        CD_CONTA_CONTABIL BIGINT,
        DESCRICAO TEXT,
        VL_SALDO_INICIAL NUMERIC(18,2),
        VL_SALDO_FINAL NUMERIC(18,2)
    );
    """)
    f.write(f"\copy {tabela} FROM '{csv_file}' DELIMITER ';' CSV NULL 'NULL' ENCODING 'UTF8';\n")

print("\n")
print(f"CSV gerado: {csv_file}")
print(f"Script SQL gerado: {sql_file}")
print("\n")

comando = input("Você deseja executar o comando para importar os dados no banco? (Digite 'sim' para executar ou 'não' para cancelar): ")
if comando.lower() == 'sim' or comando.lower() == 's' or comando.lower() == 'y' or comando.lower() == 'yes':
    inserir_dados_no_postgres()    
else:
    print("Ação cancelada.")
