/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Charts: typeof import('./src/components/charts/Charts.vue')['default']
    Filters: typeof import('./src/components/charts/Filters.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    HealthCharts: typeof import('./src/components/HealthCharts.vue')['default']
    HealthChartsContainer: typeof import('./src/components/HealthChartsContainer.vue')['default']
    HealthData: typeof import('./src/components/HealthData.vue')['default']
    HealthFilters: typeof import('./src/components/HealthFilters.vue')['default']
    HealthHeader: typeof import('./src/components/HealthHeader.vue')['default']
    HealthMap: typeof import('./src/components/HealthMap.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    Map: typeof import('./src/components/charts/Map.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
